# Generated by Django 4.2 on 2023-05-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'modelo',
                'managed': False,
            },
        ),
    ]
