# Generated by Django 4.2 on 2023-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_marca_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'auto',
                'managed': False,
            },
        ),
    ]
