# Generated by Django 4.2 on 2023-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ap_pat', models.CharField(max_length=30)),
                ('ap_mat', models.CharField(max_length=30)),
            ],
        ),
    ]
